spring.application.name: backend-is-also-beautiful
server.port: 8080
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  metrics:
    tags:
      application: ${spring.application.name}
